#-------------------------------
# General Site Settings

title: Reliability challenge workshop
logo: logo_white_bg.svg
email: arpad.rozsas@tno.nl <br> arthur.slobbe@tno.nl
phone: +31 6 15138029
address: Stieltjesweg 1, 2628 CK Delft, The Netherlands

menu:
- {name: Topic, link: 'about.html'}
- {name: Registration, link: 'registration.html'}


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: UA-156875858-1

#-------------------------------
# Hero Section

hero:
  organizer_title: Organized and hosted by
  main_title: 2<sup>nd</sup> Workshop<span>&#58;</span> Computational challenges in the reliability assessment of engineering structures
  date_title: February 24-25, 2020 <br> Delft, The Netherlands

#-------------------------------
# About (Section and Page)

# About Section
topic-title: Topic
 
blurb:  <p class="text-dark">
          The <a href="https://www.tno.nl/en/focus-areas/buildings-infrastructure-maritime/expertise-groups/structural-reliability/" target="_blank" class="btn-transparent">Department of Structural Reliability</a> at TNO is organizing a workshop on the follow-up of the <a href="https://rprepo.readthedocs.io/en/latest/" target="_blank" class="btn-transparent">Black-box Reliability Challenge 2019</a>.
          It is also the second workshop on the <i>Computational Challenges in the Reliability Assessment of Engineering Structures</i>, the <a href="https://www.reliabilitytno.com/" target="_blank" class="btn-transparent">first one</a> was held in Delft in 2018.
        </p>
        <p class="text-dark">
          The workshop will focus on<span>&#58;</span>
        </p>
        <ul class="text-dark">
          <li>Presenting  and discussing the results of the <a href="https://rprepo.readthedocs.io/en/latest/" target="_blank" class="btn-transparent">Black-box Reliability Challenge 2019</a>.</li>
          <li>Disclosing and discussing the solutions and algorithms.</li>
          <li>Discussing the possible improvements and further steps in benchmarking.</li>
          <li>Discussing general computational challenges in reliability analysis.</li>
          <li>Discussing the dissemination of the results.</li>
        </ul>
        <br>
        <p class="text-dark">
          The general aim of the workshop is to bring together researchers, practitioners, and software developers from all over the world
          to discuss challenges related to this topic, share experience, learn from each other, and to jointly find ways of solving
          these challenges.
        </p>
  
  # <p class=" text-dark">
  #        The Department of Structural Reliability at TNO (Netherlands Organization for Applied Scientific Research)
  #        is organizing a workshop on the computational challenges and aspects in the reliability analysis of engineering structures.
  #        The particular focus of the workshop is reliability problems that are <span>&#58;</span> 
  #      </p>
  #     <ol type="i">
  #       <li>high-dimensional (>40)</li>
  #       <li>have multiple failure modes</li>
  #       <li>and have small failure probabilities (10<sup>-3</sup>–10<sup>-6</sup>)</li>
  #     </ol>
  #     <br>
  #     <p class="text-dark">
  #        The aim of the workshop is to bring together researchers, practitioners, and software developers from all over the world
  #         to discuss challenges related to this topic, share experience, learn from each other, and to jointly find ways of solving
  #         these challenges. The application area is intentionally broad, we expect practitioners and researchers from all branches of engineering who face the outlined challenges, e.g. civil, mechanical, aerospace, industrial, and mechatronics engineers.
  #     </p>
  


blurb-btn-link: 'about.html'
blurb-btn-name: know more

#-------------------------------
# Registration Section

registration-title: Register for the workshop!
registration-section: <p class="font-secondary-bold mb-0 text-dark">
                Registration and participation are free! 
              </p>
              <p class="text-dark"> 
                Click on the Register button below to register for the second day of the workshop (25<sup>th</sup> of February).
                The first day (24<sup>th</sup> of February) is reserved for participants and contributors of the <a href="https://rprepo.readthedocs.io/en/latest/" target="_blank" class="btn-transparent">Black-box Reliability Challenge 2019</a>.
                If you participated and/or contributed to the challenge, but haven't received an invitation then please contact us.
              </p>

              <div class="col-lg-6 col-10 mx-auto">
                <a href="registration.html" class="btn btn-primary w-100" role="button">Register</a>
              </div>

registration-page: <p class="font-secondary-bold mb-0 text-dark">
                Registration and participation are free! 
              </p>
              <p class="text-dark"> 
                Use the form below to register for the second day of the workshop (25<sup>th</sup> of February).
                The first day (24<sup>th</sup> of February) is reserved for participants and contributors of the <a href="https://rprepo.readthedocs.io/en/latest/" target="_blank" class="btn-transparent">Black-box Reliability Challenge 2019</a>.
                If you participated and/or contributed to the challenge, but haven't received an invitation then please contact us.
              </p>
#-------------------------------
# Location Section

location-title: How to get there?

location: <p class="font-secondary-bold text-dark">
            Location</span>
          </p>
          <p class="text-dark">
            The workshop will be held in the <a href="https://www.tno.nl/nl/over-tno/locaties/locatie-delft-stieltjesweg/lid2319/" target="_blank" class="btn-transparent">TNO building at Stieltjesweg 1, 2628 CK Delft</a> that is on the TU Delft Campus.
          </p>
          <p class="font-secondary-bold text-dark">
            By car</span>
          </p>
          <p class="text-dark">
            The TU Delft Campus is easily accessible by car via the A13, exit Delft/Pijnacker and exit Delft Zuid/TU-wijk. Plan your route with <a href="https://goo.gl/maps/cxzx1UfFp4rLrUQ28" target="_blank" class="btn-transparent">Google Maps</a>.
            Parking areas are indicated on <a href="https://ca6b8504-f5c2-446f-b994-896c28e435ea.filesusr.com/ugd/a545af_60c24aeef18d4aebaa5c8a2830484110.pdf" target="_blank" class="btn-transparent">this map</a>.
          </p>
          <p class="font-secondary-bold text-dark">
            By public transport</span>
          </p>
          <p class="text-dark">
            If you come by public transport it is recommended to travel by train to Delft Central Station. There is a direct train connection between Schiphol airport and Delft. Afterwards take a bus in the direction of the TU Delft Campus.
          </p>
          <ul type="i" class="text-dark">
            <li>Bus 40, 69, 174, get off at station ‘Sport & Cultuur’. From there it is a five-minute walk to the location of the workshop.</li>
          </ul>
          <br>
          <p class="text-dark">
            Plan your trip with a <a href="https://9292.nl/en" target="_blank" class="btn-transparent">traveling assistant</a>.
          </p>

#-------------------------------
# Agenda Section

agenda-title: Agenda
agenda: <p class="font-secondary-bold text-dark">
          Day 1 (24<sup>th</sup> of February, Monday, <a href="https://www.tno.nl/nl/over-tno/locaties/locatie-delft-stieltjesweg/lid2319/" target="_blank" class="btn-transparent">Room E075, Stieltjesweg 1, 2628 CK Delft</a>)
        </p>
        <p class="font-secondary text-dark">
          A small group session for those who were contributing to and/or participating in the <a href="https://rprepo.readthedocs.io/en/latest/" target="_blank" class="btn-transparent">Black-box Reliability Challenge 2019</a>.
        </p>
        <p class="font-secondary text-dark">
          12<span>&#58;</span>00 Opening. <br>
          17<span>&#58;</span>00 Closure.
        </p>
        <br>

        <p class="font-secondary-bold text-dark">
          Day 2 (25<sup>th</sup> of February, Tuesday, <a href="https://www.tno.nl/nl/over-tno/locaties/locatie-delft-stieltjesweg/lid2319/" target="_blank" class="btn-transparent">Room P01.020, Stieltjesweg 1, 2628 CK Delft</a>)
        </p>
        <p class="font-secondary text-dark">
          A larger group session for anyone who is interested. Presenting the aggregated results and the solutions of the participants. Additional presentations are also welcome (limited only by the available time). Please indicate you interest in giving a presentation in the registration form and we will contact you.
        </p>
        <p class="font-secondary text-dark">
          9<span>&#58;</span>00 Opening. <br>
          17<span>&#58;</span>00 Closure.
        </p>

        <p class="font-secondary-bold text-dark"> 
            The agenda of both days will be updated soon and published here.
        </p>
        <hr>
        <hr>


#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: arpad.rozsas@tno.nl