#-------------------------------
# General Site Settings

title: Reliability challenge workshop
logo: logo_white_bg.png
email: arpad.rozsas@tno.nl <br> arthur.slobbe@tno.nl
phone: +31 6 16340912
address: Stieltjesweg 1, 2628 CK Delft, The Netherlands

menu:
- {name: Topic, link: 'about.html'}
- {name: Registration, link: '/registration/'}
# - {name: Blog, link: '/blog/'}
# - {name: Portfolio, link: '/portfolio/'}
# - {name: Contact, link: '/contact/'}


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: UA-156875858-1


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Hero Section

hero:
  hero-title: Workshop <span>&#58;</span> Computational challenges in the reliability assessment of engineering structures
  hero-title2: February 24-25, 2020 <br> Delft, The Netherlands

# social:
# - {icon: "ti-facebook", link: "#"}
# - {icon: "ti-instagram", link: "#"}
# - {icon: "ti-dribbble", link: "#"}
# - {icon: "ti-twitter", link: "#"}


#-------------------------------
# About (Section and Page)

# About Section
topic-title: Topic
 
blurb:  <p class="font-secondary paragraph-lg text-dark">
          The <a href="https://www.tno.nl/en/focus-areas/buildings-infrastructure-maritime/expertise-groups/structural-reliability/" target="_blank" class="btn-transparent">Department of Structural Reliability</a> at TNO is organizing a workshop on the follow-up of the <a href="https://rprepo.readthedocs.io/en/latest/" class="btn-transparent">Black-box Reliability Challenge 2019</a>.
          It is also the second workshop on the <i>Computational Challenges in the Reliability Analysis of Engineering Structures</i>, the <a href="https://www.reliabilitytno.com/" target="_blank" class="btn-transparent">first one</a> was held in Delft in 2018.
        </p>
        <p class="font-secondary paragraph-lg text-dark">
          The workshop will focus on
        </p>
        <ul>
          <li>Presenting  and discussing the results of the <a href="https://rprepo.readthedocs.io/en/latest/" target="_blank" class="btn-transparent">Black-box Reliability Challenge 2019</a>.</li>
          <li>Disclosing and discussing the solutions and algorithms.</li>
          <li>Discussing the possible improvements and further steps in benchmarking.</li>
          <li>Discussing general computational challenges in reliability analysis.</li>
        </ul>
        <br>
        <p class="font-secondary paragraph-lg text-dark">
          The general aim of the workshop is to bring together researchers, practitioners, and software developers from all over the world
          to discuss challenges related to this topic, share experience, learn from each other, and to jointly find ways of solving
          these challenges.
        </p>
  
  # <p class="font-secondary paragraph-lg text-dark">
  #        The Department of Structural Reliability at TNO (Netherlands Organization for Applied Scientific Research)
  #        is organizing a workshop on the computational challenges and aspects in the reliability analysis of engineering structures.
  #        The particular focus of the workshop is reliability problems that are <span>&#58;</span> 
  #      </p>
  #     <ol type="i">
  #       <li>high-dimensional (>40)</li>
  #       <li>have multiple failure modes</li>
  #       <li>and have small failure probabilities (10<sup>-3</sup>–10<sup>-6</sup>)</li>
  #     </ol>
  #     <br>
  #     <p class="font-secondary paragraph-lg text-dark">
  #        The aim of the workshop is to bring together researchers, practitioners, and software developers from all over the world
  #         to discuss challenges related to this topic, share experience, learn from each other, and to jointly find ways of solving
  #         these challenges. The application area is intentionally broad, we expect practitioners and researchers from all branches of engineering who face the outlined challenges, e.g. civil, mechanical, aerospace, industrial, and mechatronics engineers.
  #     </p>
  


blurb-btn-link: 'about.html'
blurb-btn-name: know more


# About Page

# # Work Process Section
# work-process:
#   - title : "Research and Plan"
#     icon : "assets/images/icons/plan.png"
#     content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    
#   - title : "Design and Develop"
#     icon : "assets/images/icons/design.png"
#     content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    
#   - title : "Deliver"
#     icon : "assets/images/icons/print.png"
#     content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."


# # My Team Section
# team:
#   - title : "Jack Schenziwe"
#     image : "assets/images/team/member-1.png"
#     designation : "Project Manager"
    
#   - title : "Julias Carlie"
#     image : "assets/images/team/member-2.png"
#     designation : "Web Developer"
    
#   - title : "John Doe"
#     image : "assets/images/team/member-3.png"
#     designation : "Designer"


#-------------------------------
# Registration Section

registration-title: Register for the workshop!
registration: <p class="font-secondary-bold paragraph-lg text-dark">
                Registration and participation are free! 
              </p>
              <p class="font-secondary paragraph-lg text-dark"> 
                Use the form below to register for the second day of the workshop (25th of February). <br>
                The first day (24th of February) is reserved for participants and contributors of the <a href="https://rprepo.readthedocs.io/en/latest/" target="_blank" class="btn-transparent">Black-box Reliability Challenge 2019</a>. If you are participants and/or contributors, and haven't received an invitation then please contact us.
              </p>


#-------------------------------
# Location Section

location-title: How to get there?

location: <p class="font-secondary paragraph-lg text-dark">
            The workshop will take place in Delft, The Netherlands. The final venue is to be confirmed but it surely will be close to the TU Delft Campus.
          </p>
          <p class="font-secondary-bold paragraph-lg text-dark"> 
            The address and a how-to-get-there guide will be published here.
          </p>
# location: <p class="font-secondary-bold paragraph-lg text-dark">Location <span>&#58;</span></p>
#         <p class="font-secondary paragraph-lg text-dark">The workshop will be held at the Business Centre Delftech, Delftechpark 29,
#          2628 Delft, which is right next to the campus of TU Delft.</p>
#         <p class="font-secondary-bold paragraph-lg text-dark">By car <span>&#58;</span></p>
#         <p class="font-secondary paragraph-lg text-dark">The TU Delft campus is easily accessible by car via the A13, exit
#          Delft/Pijnacker and exit Delft Zuid/TU-wijk. Plan your route with <a href="https://goo.gl/maps/cxzx1UfFp4rLrUQ28" target="_blank" class="btn-transparent">Google Maps</a>.
#          Parking areas are indicated on <a href="https://ca6b8504-f5c2-446f-b994-896c28e435ea.filesusr.com/ugd/a545af_60c24aeef18d4aebaa5c8a2830484110.pdf" target="_blank" class="btn-transparent">this map</a>.</p>
#         <p class="font-secondary-bold paragraph-lg text-dark">By public transport <span>&#58;</span></p>
#         <p class="font-secondary paragraph-lg text-dark">If you come by public transport it is recommended to travel by train
#          to Delft Central Station. There is a direct train connection between Schiphol airport and Delft. Afterwards take the bus towards the TU Campus.</p>
#         <ul type="i" class="font-secondary paragraph-lg text-dark">
#           <li>Bus 40, 69, 174, get off at station ‘Sport & Cultuur’. From here it is an eight-minute walk to the location of the workshop.</li>
#         </ul>
#         <br>
#         <p class="font-secondary paragraph-lg text-dark"> Plan your trip with the <a href="https://9292.nl/en" target="_blank" class="btn-transparent">traveling assistant</a>.</p>

#-------------------------------
# Agenda Section

agenda-title: Agenda
agenda: <p class="font-secondary-bold paragraph-lg text-dark">
          Day 1 (24th of February, Monday)
        </p>
        <p class="font-secondary paragraph-lg text-dark">
          A small group session for those who were contributing to and/or participating in the <a href="https://rprepo.readthedocs.io/en/latest/" target="_blank" class="btn-transparent">Black-box Reliability Challenge 2019</a>.
        </p>
        <p class="font-secondary paragraph-lg text-dark">
          12<span>&#58;</span>00 Opening. <br>
          17<span>&#58;</span>00 Closure.
        </p>
        <br>

        <hr>
        <p class="font-secondary-bold paragraph-lg text-dark">
          Day 2 (25th of February, Tuesday)
        </p>
        <p class="font-secondary paragraph-lg text-dark">
          A larger group session for anyone who is interested. Presenting the aggregated results and the solutions of the participants. Additional presentations are also welcome (limited only by the available time). Please indicate you interest in giving a presentation in the registration form and we will contact you.
        </p>
        <p class="font-secondary paragraph-lg text-dark">
          9<span>&#58;</span>00 Opening. <br>
          17<span>&#58;</span>00 Closure.
        </p>

        <p class="font-secondary-bold paragraph-lg text-dark"> 
            The agenda of both days will be updated soon and published here.
        </p>


#-------------------------------

#-------------------------------
# Skills Section

# skills-title: Skills
# skills:
# - {name: Web Design, color: '#fdb157', value: '90%'}
# - {name: Logo Design, color: '#9473e6', value: '60%'}
# - {name: After Effects, color: '#bdecf6', value: '80%'}
# - {name: Web App, color: '#ffbcaa', value: '70%'}


#-------------------------------
# Exprerience Section

# experience-title: Experience
# experience:
# - {name: Junior UX Designer, icon: 'icon-1.png', date: 'Jan 2007 - Feb 2009', organization: 'WEBEX'}
# - {name: UX & UI Designer, icon: 'icon-2.png', date: 'Mar 2009 - Aug 2014', organization: 'AUGMEDIX'}
# - {name: Senior UI Designer, icon: 'icon-3.png', date: 'Sep 2014 - Present', organization: 'THEMEFISHER'}


#-------------------------------
# Education Section

# education-title: Education
# education:
# - {name: Marters in UX Design, date: '2006', organization: 'Masassusets Institute of Technology'}
# - {name: Honours in Fine Arts, date: '2004', organization: 'Harvard University'}
# - {name: Higher Secondary Certificat, date: '2000', organization: 'Cardiff School'}
# - {name: Secondary School Certificate, date: '1998', organization: 'Cardiff School'}


#-------------------------------
# Services Section

# services-title: Services
# services:
# - {
#     name: UI Design,
#     icon: ti-palette,
#     description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
#     active: # Add true to select section
#   }
# - {
#     name: UX Design,
#     icon: ti-vector,
#     description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
#     active: true # Add true to select section
#   }
# - {
#     name: Interaction Design,
#     icon: ti-panel,
#     description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
#     active: # Add true to select section
#   }



#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
# portfolio-home-items:
#   - image : "assets/images/portfolio/item-1.png"
#     url: "#"
    
#   - image : "assets/images/portfolio/item-2.png"
#     url: "#"
    
#   - image : "assets/images/portfolio/item-3.png"
#     url: "#"
    
#   - image : "assets/images/portfolio/item-4.png"
#     url: "#"
    
#   - image : "assets/images/portfolio/item-5.png"
#     url: "#"


# Portfolio Page
# portfolio-label:
# - {
#     title : "UI/UX Design",
#     type : "design"
#   }
# - {
#     title : "BRANDING",
#     type : "branding"
#   }
# - {
#     title : "ILLUSTRATION",
#     type : "illustration"
#   }

# portfolio-items:
#   - image : "assets/images/portfolio/item-1.png"
#     url: "#"
#     portfolio-type:
#      - type: "design"
#      - type: "illustration"
      
#   - image : "assets/images/portfolio/item-2.png"
#     url: "#"
#     portfolio-type:
#       - type: "branding"
      
#   - image : "assets/images/portfolio/item-3.png"
#     url: "#"
#     portfolio-type:
#       - type: "illustration"
      
#   - image : "assets/images/portfolio/item-6.png"
#     url: "#"
#     portfolio-type:
#       - type: "design"
#       - type: "branding"
      
#   - image : "assets/images/portfolio/item-8.png"
#     url: "#"
#     portfolio-type:
#       - type: "illustration"
      
#   - image : "assets/images/portfolio/item-5.png"
#     url: "#"
#     portfolio-type:
#       - type: "design"
      
#   - image : "assets/images/portfolio/item-1.png"
#     url: "#"
#     portfolio-type:
#       - type: "branding"
      
#   - image : "assets/images/portfolio/item-3.png"
#     url: "#"
#     portfolio-type:
#       - type: "design"
#       - type: "illustration"
#       - type: "branding"
      
#   - image : "assets/images/portfolio/item-7.png"
#     url: "#"
#     portfolio-type:
#       - type: "illustration"


#-------------------------------
# Testimonials Section

# testimonial-items:
#   - name: "Jesica Gomez"
#     image: "assets/images/testimonial/client-1.png"
#     designation : "CEO, Funder"
#     content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."
    
#   - name: "Jesica Gomez"
#     image: "assets/images/testimonial/client-1.png"
#     designation: "CEO, Funder"
#     content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."
    
#   - name: "Jesica Gomez"
#     image: "assets/images/testimonial/client-1.png"
#     designation: "CEO, Funder"
#     content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."


#-------------------------------
# Client Slider Section

# client-slider-items:
#   - logo: "assets/images/clients-logo/client-logo-1.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-2.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-3.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-4.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-5.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-1.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-2.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-3.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-4.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-5.png"
#     url: "#"

#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: arpad.rozsas@tno.nl